language: java

sudo: true

script:
  - ./gradlew check
  - ./gradlew assemble
  - ./gradlew setupCIWorkspace
  - ./gradlew build

jdk:
  - oraclejdk8
  - openjdk8

 before_install:
 - chmod +x gradlew